var userInfoJson = {
    "login": "abedsujan",
    "id": 1411058,
    "node_id": "MDQ6VXNlcjE0MTEwNTg=",
    "avatar_url": "https://avatars2.githubusercontent.com/u/1411058?v=4",
    "gravatar_id": "",
    "url": "https://api.github.com/users/abedsujan",
    "html_url": "https://github.com/abedsujan",
    "followers_url": "https://api.github.com/users/abedsujan/followers",
    "following_url": "https://api.github.com/users/abedsujan/following{/other_user}",
    "gists_url": "https://api.github.com/users/abedsujan/gists{/gist_id}",
    "starred_url": "https://api.github.com/users/abedsujan/starred{/owner}{/repo}",
    "subscriptions_url": "https://api.github.com/users/abedsujan/subscriptions",
    "organizations_url": "https://api.github.com/users/abedsujan/orgs",
    "repos_url": "https://api.github.com/users/abedsujan/repos",
    "events_url": "https://api.github.com/users/abedsujan/events{/privacy}",
    "received_events_url": "https://api.github.com/users/abedsujan/received_events",
    "type": "User",
    "site_admin": false,
    "name": "Abed Sujan",
    "company": null,
    "blog": "http://abedsujan.com",
    "location": "Copenhagen, Denmark",
    "email": null,
    "hireable": null,
    "bio": null,
    "public_repos": 51,
    "public_gists": 19,
    "followers": 2,
    "following": 8,
    "created_at": "2012-02-06T00:58:34Z",
    "updated_at": "2018-05-05T15:46:01Z"
};